document.write('<!DOCTYPE html>');
document.write('<html lang="en">');
document.write('<head>');
document.write('    <meta charset="UTF-8">');
document.write('    <meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('');
document.write('<html lang="en">');
document.write('<html>');
document.write('<html>');
document.write('<title/>KeepHiring</title>');
document.write('<link rel="stylesheet" href="loading.html">');
document.write('<link rel="stylesheet" href="Mobileview.html">');
document.write('<link rel="stylesheet" href="script.js">');
document.write('<link rel="stylesheet" href="style.css">');
document.write('');
document.write('');
document.write('');
document.write('</head>');
document.write('<body>');
document.write('');
document.write('');
document.write('<div class="container">');
document.write('	<div class="navbar">');
document.write('		<img src="logo.png" width="85" height="50 "class="logo.png">');
document.write('		<nav>');
document.write('			<meta charset="UTF-8">');
document.write('			<meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('			<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>');
document.write('			<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>');
document.write('			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>');
document.write('			');
document.write('			<div>');
document.write('				<ul>');
document.write('					<li><button onclick="location.href=\'index.html\'">Home</button></li>');
document.write('					<li><button onclick="location.href=\'Aboutus.html\'">About Us</button></li>');
document.write('					<li><button onclick="location.href=\'Services.html\'">Services</button></li>');
document.write('					<li><button onclick="location.href=\'Contact V15.html\'">Contact Us</button></li>');
document.write('				</ul>');
document.write('				');
document.write('		</div>');
document.write('	</nav>');
document.write('	');
document.write('	<div class="contents">');
document.write('	<h1>We are IT Recruiting Expertise <br>we specialize in connecting businesses </h1>');
document.write('	<h3>with the best IT professionals in the industry.</h3>');
document.write('	<p>Our experienced team of recruiters are adept at identifying</p>');
document.write('	<h2>top talent that aligns with your specific requirements and company culture</h2>');
document.write('');
document.write('');
document.write('<img src="Tech.png" class="feature-img" width="580" height="90 "class="logo.png">');
document.write('');
document.write('<div class="middle">');
document.write('	<div class="middlecontent">');
document.write('		<img src="bgck1.jpg"');
document.write('	</div>');
document.write('');
document.write('	');
document.write('<div class="contents1">');
document.write('<p1>KeepHiring Mentors Staffing Solutions</p1>');
document.write('<p2>10+ years of experience in executive search & placements .Catering to diverse nature of business from large corporates to SMEs and startups, spread across various verticals, functions, geographies.</p2>');
document.write('</div>');
document.write('');
document.write('');
document.write('');
document.write('<div class="slider-container">');
document.write('	<div class="slider">');
document.write('		<div class="slide">');
document.write('			<li><img src="slider1.jpg" alt="slide 1"></li>');
document.write('		</div>');
document.write('		<div class="slide">');
document.write('			<li><img src="slider2.jpg" alt="slide 2"></li>');
document.write('		</div>');
document.write('		<div class="slide">');
document.write('			<li><img src="slider3.jpg" alt="slide 3"></li>');
document.write('		</div>');
document.write('	</div>');
document.write('	<div class="prev">&#10094;</div></span>');
document.write('	<div class="next">&#10095;</div></span>');
document.write('</div>');
document.write('');
document.write('<script src="script.js"></script>');
document.write('</body>');
document.write('</html>');
document.write('');